### ISSUE TITLE
About the name

### ISSUE THREAD

**Issue by jancborchardt** [Leandros/ownDrop#1]
First off: This is awesome! :)

The only thing I am concerned about is the name. I searched on Twitter to look if the app has already been written about – there I found that the CloudApp client »ClouDrop« used to be named »DropCloud« but changed their name: https://twitter.com/search?q=dropcloud&src=typd
I don’t now why they renamed and couldn’t find any info about it. Might have even been that they were requested to change the name.

In any case, the name is attached to that app, and searches on Google etc bring that up and will continue to, rather than your app. So it would probably be wise to rename.

I don’t have any good/short ideas right now except »ownDrop«. ;)

(By the way: You should come to the ownCloud contributor conf, August 26–31 in Berlin!)

**Comment by jancborchardt** [comment]
(@Leandros the name is basically the only thing keeping me hesitant about tweeting and publishing it from the ownClouders Twitter account.)

**Comment by Leandros** [comment]
Thanks a lot for the suggestion. I like 'ownDrop'. I think it fit's the app, I'am gonna rename it.

**Comment by jancborchardt** [comment]
That was quick, thanks! :) Tweeted: https://twitter.com/ownClouders/status/472307893593989120

**Comment by jancborchardt** [comment]
@Leandros props on the mass of people retweeting your app! :)
