### ISSUE TITLE
Upload failed

### ISSUE THREAD

**Issue by webstylr** [Leandros/ownDrop#10]
If i try to upload a file, i get:

30.05.14 13:30:43,113 ownDrop[14251]: Upload Error: Error Domain=NSURLErrorDomain Code=-999 "Abgebrochen" UserInfo=XXXXXXXX {NSErrorFailingURLKey=https://cloud.mydomain.com//remote.php/webdav/image.jpg, NSLocalizedDescription=Abgebrochen, NSErrorFailingURLStringKey=https://cloud.mydomain.com//remote.php/webdav/image.jpg}

My Preferences are:
https://cloud.mydomain.com
Path empty

On a sidenote: if i close owndrop and reopen it, the password field in preferences is empty.
Is this normal behaviour?

**Comment by webstylr** [comment]
Thanks for the info @JohnyGoerend !
Forgot to mention i'm using a self-signed certificate. Syncing /uploading files with owncloud.app works as expected though.

**Comment by Leandros** [comment]
Self signed certificates are currently not supported. I'll add a switch to the preferences to allow them.

**Comment by webstylr** [comment]
Thanks for the headsup! Will wait then.

**Comment by Leandros** [comment]
Added in a9ef950cf211de1914c2d4e8c6ba378977ddaef5
