### ISSUE TITLE
uploads not working with v0.7 – working fine with 0.6

### ISSUE THREAD

**Issue by kanedo** [Leandros/ownDrop#16]
Hi
I've updated to the recent version .7 but it stopped working. I'm really not sure why, but no upload succeeds. 
I've downgraded to .6 to ensure its not my owncloud installation and it works just fine.

**Comment by Leandros** [comment]
Could you get me a log of the error.
On your mac is an application called "Console". Open it, and search for "ownDrop".

**Comment by kanedo** [comment]
after reinstalling version 0.7 the first upload worked. I retried it and got a timeout:

```
31.08.14 12:02:01,443 ownDrop[2118]: Upload Error: Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo=0x7f8cc486d0d0 {NSUnderlyingError=0x7f8cc4873eb0 "The request timed out.", NSErrorFailingURLStringKey=https://domain.tld/remote.php/webdav//Screenshots/Screen%20Shot%202014-08-31%20at%2012.00.52.png, NSErrorFailingURLKey=https://domain.tld/remote.php/webdav//Screenshots/Screen%20Shot%202014-08-31%20at%2012.00.52.png, NSLocalizedDescription=The request timed out.}
```

**Comment by Leandros** [comment]
Could you check, if your credentials are still right in place?

**Comment by kanedo** [comment]
I’ve checked the settings and had a look at the Keychain entry own drop creates: seems to be correct

**Comment by Leandros** [comment]
Well, a timeout is most likely not related to ownDrop itself, but to either your internet connection or your server where ownCloud is running.
I uploaded about 10 items consecutively now, and every single one worked perfectly.

**Comment by Leandros** [comment]
Also, I haven't changed anything in the upload code between 0.6 and 0.7. However, still investigating. Any log you can catch is helpful.

**Comment by kanedo** [comment]
I think I know where it fails
The log says something like this:

``` json
{
    "reqId" : "5402f5ec2b2e8",
    "app" : "PHP",
    "message" : "Undefined offset: 1 at \/var\/www\/virtual\/\/lib\/private\/files\/stream\/dir.php#29",
    "level" : 3,
    "time" : "2014-08-31T10:16:49+00:00",
    "method" : "PUT",
    "url" : "\/remote.php\/webdav\/\/Screenshots\/Screen%20Shot%202014-08-31%20at%2012.15.37.png"
}
```

My setup was, that I upload the screenshots in a mounted google drive which is located in `/Screenshots`and this seems to cause the timeouts because something went wrong between owncloud and gdrive. I changed the location to `/` and it works just fine

**Comment by Leandros** [comment]
Great!
Unrelated to this issue, but which ownCloud version are you running?

**Comment by kanedo** [comment]
I’m running ownCloud 7.0.2 (stable)

Thanks for your fast help!
