### ISSUE TITLE
Instant link creation before full upload

### ISSUE THREAD

**Issue by ElyFornoville** [Leandros/ownDrop#24]
Hi,
the main reason we are using dropbox to share files is that when you are syncing a file with dropbox you already have the option to create a link and share that link with your clients.

Is it possible to do this with ownDrop?
Let your file sync with ownCloud but already create the link to email to your clients.

Regards,
Ely

**Comment by Leandros** [comment]
If I recall correctly, the ownCloud API requires the file to be present to create a share link. You can find the code for calling the ownCloud API [here](https://github.com/Leandros/ownDrop/blob/develop/DropCloud/CloudAPI/AGCloudCommunication.m#L89). You're free to try to share a file without being there. (I might try it as well, if I can find some time)

**Comment by ElyFornoville** [comment]
Thank you. I will check it out.

**Comment by ElyFornoville** [comment]
Would be cool if you can try it. 
Let me know.
