### ISSUE TITLE
Renaming the target from DropCloud to ownDrop broke 'pod install'

### ISSUE THREAD

**Issue by oldskirt** [Leandros/ownDrop#8]
(OS X 10.9.3, ruby 2.0.0, gem 2.0.14, pod 0.33.1)

When doing a 'pod install' as per the README, this error message comes up:

```
[!] Unable to find a target named `DropCloud`
```

This happened, I guess, because of the project rename and the .xcodeproj target now being "ownDrop".

**Comment by russianryebread** [comment]
For a temporary fix, you can run `sed -i .bak 's/"DropCloud"/"ownDrop"/' Podfile` from within the working directory

**Comment by Leandros** [comment]
Fixed in 3c2973f094fc8f0d7b8708e8014a17037709c382
