### ISSUE TITLE
Credentials are saved unencrypted in defaults

### ISSUE THREAD

**Issue by oldskirt** [Leandros/ownDrop#9]
Any (non-sandboxed) process can read the user's defaults. So saving the ownCloud credentials as basically plain text is a little irresponsible. The Keychain exists for a reason.

**Comment by Leandros** [comment]
I'am aware of this and I know the keychain, it'll be changed in a future version.

**Comment by Leandros** [comment]
Fixed in f1d2a079b60ae815220a7d51b3d1618eef8d0c72
